# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' K-means clustering
#'
#' K-means clustering algorithm for the given data matrix with the number
#' of clusters given.
#'
#' @param data_mat numeric data matrix, [number of samples] x  [number of features]
#' @param N_centers number of clusters
#'
#' @return Vector of cluster assignments, [number of samples]
#' @useDynLib CS599Clustering, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
#' 
#' @examples
#' kmeansclust_interface(as.matrix(iris[,1:2]),3)
kmeansclust_interface <- function(data_mat, N_centers) {
    .Call(`_CS599Clustering_kmeansclust_interface`, data_mat, N_centers)
}

